spring:
  application:
    name: risk-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: flowguard-risk
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        "[spring.json.trusted.packages]": "com.flowguard.risk.event"
        "[spring.json.type.mapping]": "transaction-created:com.flowguard.risk.event.TransactionCreatedEvent"

flowguard:
  kafka:
    topics:
      transaction-created: transaction.created